runtime: nodejs10

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 1
  max_pending_latency: 2000ms

handlers:
  - url: /_nuxt
    static_dir: .nuxt/dist/client

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files: static/\1
    upload: app/static/.*\.(gif|png|jpg|ico|txt)$

  - url: /sw.js
    static_files: app/static/sw.js
    upload: app/static/sw.js

  - url: /.*
    script: auto
    secure: always

env_variables:
  NUXT_HOST: '0.0.0.0'
  NUXT_PORT: '8080'
