steps:
  - name: 'alpine'
    args: ['echo', '${_ENVIRONMENT}']
  - name: node:10.15.1
    entrypoint: yarn
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/gcloud'
    args: ['source', 'repos', 'clone', 'default']
