steps:
  - name: 'alpine'
    args: ['echo', '${_ENVIRONMENT}']
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
  - name: 'gcr.io/$PROJECT_ID/gcloud'
    args: ['source', 'repos', 'clone', 'default']
