name: devCI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.18.0]
    steps:
    - uses: actions/checkout@v1
    - name: Run tests with ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build
      env:
        FB_API_KEY: ${{ secrets.FB_API_KEY }}
        FB_APP_ID: ${{ secrets.FB_APP_ID }}
        FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
        FB_DATABASE_URL: ${{ secrets.FB_DATABASE_URL }}
        FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}
        FB_MESSAGING_SENDER_ID: ${{ secrets.FB_MESSAGING_SENDER_ID }}
        FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
        FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
      run: |
        yarn install
        NODE_ENV=production yarn run build:prod
    - name: GAE deploy
      run: |
        echo 'github-actions@stadium-gourmet-list.iam.gserviceaccount.com' | gcloud auth activate-service-account --key-file stadium-gourmet-list-eda668c12250.json
        gcloud app deploy app.yaml --project stadium-gourmet-list
      env:
        CI: true
